-- Run after database/schema.sql with psql (client-side import):
-- psql -d sme_credit_risk -f database/seed.sql
-- If psql starts outside the repository root, replace the relative path below.
-- Server-side COPY is an alternative only when the PostgreSQL server can read its path.
BEGIN;
CREATE TEMP TABLE sme_loan_applications_staging (
 application_id VARCHAR(16),customer_id VARCHAR(16),application_date DATE,business_type VARCHAR(32),business_age_years NUMERIC(4,1),number_of_employees INTEGER,monthly_revenue NUMERIC(14,2),annual_revenue NUMERIC(14,2),requested_loan_amount NUMERIC(14,2),loan_tenure_months INTEGER,loan_purpose VARCHAR(32),existing_loans INTEGER,existing_monthly_debt NUMERIC(14,2),debt_to_income_ratio NUMERIC(5,3),bureau_score INTEGER,credit_history_years NUMERIC(4,1),previous_defaults INTEGER,collateral_value NUMERIC(14,2),bank_account_age_years NUMERIC(4,1),application_status VARCHAR(16),credit_review_date DATE,approval_date DATE,disbursement_date DATE,approved_amount NUMERIC(14,2),outstanding_balance NUMERIC(14,2),days_past_due INTEGER,missed_payments INTEGER,total_payments INTEGER,loan_status VARCHAR(20),default_flag SMALLINT
) ON COMMIT DROP;
\copy sme_loan_applications_staging FROM 'data/raw/sme_loan_applications.csv' WITH (FORMAT csv, HEADER true, NULL '')
INSERT INTO customers(customer_id) SELECT DISTINCT customer_id FROM sme_loan_applications_staging;
INSERT INTO loan_applications(application_id,customer_id,application_date,business_type,business_age_years,number_of_employees,monthly_revenue,annual_revenue,credit_history_years,bank_account_age_years,requested_loan_amount,loan_tenure_months,loan_purpose) SELECT application_id,customer_id,application_date,business_type,business_age_years,number_of_employees,monthly_revenue,annual_revenue,credit_history_years,bank_account_age_years,requested_loan_amount,loan_tenure_months,loan_purpose FROM sme_loan_applications_staging;
INSERT INTO credit_assessments(application_id,existing_loans,existing_monthly_debt,debt_to_income_ratio,bureau_score,previous_defaults,collateral_value) SELECT application_id,existing_loans,existing_monthly_debt,debt_to_income_ratio,bureau_score,previous_defaults,collateral_value FROM sme_loan_applications_staging;
INSERT INTO loan_decisions(application_id,application_status,credit_review_date,approval_date,approved_amount,disbursement_date) SELECT application_id,application_status,credit_review_date,approval_date,approved_amount,disbursement_date FROM sme_loan_applications_staging;
INSERT INTO loan_performance(application_id,outstanding_balance,days_past_due,missed_payments,total_payments,loan_status,default_flag) SELECT application_id,outstanding_balance,days_past_due,missed_payments,total_payments,loan_status,default_flag FROM sme_loan_applications_staging;
COMMIT;
-- Expected: 5,885 customers; 10,000 rows in each application-linked table.
SELECT (SELECT COUNT(*) FROM customers) AS customers,(SELECT COUNT(*) FROM loan_applications) AS applications,(SELECT COUNT(*) FROM credit_assessments) AS credit_assessments,(SELECT COUNT(*) FROM loan_decisions) AS decisions,(SELECT COUNT(*) FROM loan_performance) AS performance_rows;
SELECT application_id,COUNT(*) AS duplicate_count FROM loan_applications GROUP BY application_id HAVING COUNT(*) > 1;
SELECT COUNT(*) FILTER (WHERE c.application_id IS NULL) AS assessments_without_application,COUNT(*) FILTER (WHERE d.application_id IS NULL) AS decisions_without_application,COUNT(*) FILTER (WHERE p.application_id IS NULL) AS performance_without_application FROM loan_applications a FULL OUTER JOIN credit_assessments c USING(application_id) FULL OUTER JOIN loan_decisions d USING(application_id) FULL OUTER JOIN loan_performance p USING(application_id);
-- R-approved rate definition: statuses Approved or Disbursed / all applications.
SELECT COUNT(*) AS applications,COUNT(*) FILTER(WHERE d.application_status='Disbursed') AS disbursed,COUNT(*) FILTER(WHERE d.application_status='Rejected') AS rejected,COUNT(*) FILTER(WHERE p.default_flag=1) AS defaults_among_disbursed,ROUND(100.0*COUNT(*) FILTER(WHERE d.application_status IN ('Approved','Disbursed'))/COUNT(*),2) AS approval_rate_pct,ROUND(100.0*COUNT(*) FILTER(WHERE d.application_status='Rejected')/COUNT(*),2) AS rejection_rate_pct,ROUND(100.0*COUNT(*) FILTER(WHERE d.application_status='Disbursed')/COUNT(*),2) AS disbursement_rate_pct,ROUND(100.0*COUNT(*) FILTER(WHERE p.default_flag=1)/NULLIF(COUNT(*) FILTER(WHERE d.application_status='Disbursed'),0),2) AS default_rate_disbursed_pct FROM loan_applications a JOIN loan_decisions d USING(application_id) JOIN loan_performance p USING(application_id);
SELECT COUNT(*) FILTER(WHERE ca.bureau_score IS NULL) AS null_bureau_score,COUNT(*) FILTER(WHERE ca.collateral_value IS NULL) AS null_collateral_value,COUNT(*) FILTER(WHERE a.number_of_employees IS NULL) AS null_number_of_employees,COUNT(*) FILTER(WHERE a.bank_account_age_years IS NULL) AS null_bank_account_age_years,COUNT(*) FILTER(WHERE d.credit_review_date IS NULL) AS null_credit_review_date,COUNT(*) FILTER(WHERE d.approval_date IS NULL) AS null_approval_date,COUNT(*) FILTER(WHERE d.disbursement_date IS NULL) AS null_disbursement_date FROM loan_applications a JOIN credit_assessments ca USING(application_id) JOIN loan_decisions d USING(application_id);
SELECT COUNT(*) FILTER(WHERE d.approved_amount>a.requested_loan_amount) AS approved_exceeds_requested,COUNT(*) FILTER(WHERE d.application_status<>'Disbursed' AND (p.default_flag<>0 OR p.loan_status<>'Not Disbursed' OR p.outstanding_balance<>0 OR p.days_past_due<>0 OR p.missed_payments<>0 OR p.total_payments<>0)) AS nondisbursed_performance_violations,COUNT(*) FILTER(WHERE p.default_flag=1 AND d.application_status<>'Disbursed') AS default_not_disbursed,COUNT(*) FILTER(WHERE p.default_flag=1 AND p.loan_status<>'Default') AS default_status_mismatch FROM loan_applications a JOIN loan_decisions d USING(application_id) JOIN loan_performance p USING(application_id);
